//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "eu-central-1_O9NR2K2dj"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "6vv8nf5m0hcdv3jr7kqo2s41ps"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .EUCentral1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1tt71o2m9efob4rn3eae9p7e8id6r1mshv7slvvl63bngkh35s1m"

// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .EUCentral1
